### ISSUE TITLE
Binarised mask for continuous value tiers

### ISSUE THREAD

**Issue by mvalstar** [hcmlab/nova#114]
It would be nice to be able to create a binarised version of a continuous valued annotation, by providing/setting a threshold. Either as a separate (linked) tier, or as a flip-switch of an existing tier, where you can flip between the continuous and binary view. This would be useful in particular for automatic predictions that output a likelihood, which would require some threshold set for decision making.

**Comment by tobiasbaur** [comment]
Hello Michel,

it is already possible to convert a continuous annotation to a discrete one, by setting thresholds and labels for classes (select continuous tier -> Menu: Tier -> convert  to discrete). I do agree that it would be nice to have the possibility to switch between both views.

**Comment by mvalstar** [comment]
Super duper.

I guess it's important for you to explain all features to me before I demo
it. Tuesday am?

**Comment by tobiasbaur** [comment]
In commit #132 the default behaviour was changed to create a new discrete tier, instead of overwritting the continuous one, so now it is possible to have them both open at the same time
![contier](https://cloud.githubusercontent.com/assets/10667369/22156955/d3c75fc6-df35-11e6-9a9b-0da9b2e926d2.png)
