### ISSUE TITLE
Close button, doesn't give option to cancel close

### ISSUE THREAD

**Issue by ThomasSmith3** [hcmlab/nova#133]
The close button for the main program does not give the option to cancel the close procedure and carry on with working. I know it currently asks to save open thing but you still have to load the program if it is accidentally closed.

**Comment by tobiasbaur** [comment]
That's true, on the other hand it might get a bit annoying to ask everytime the app is closed?

**Comment by ThomasSmith3** [comment]
Generally programs ask if you want to quit if the current session hasn't been saved, but if it has already then it just quits.

**Comment by tobiasbaur** [comment]
added a dialog in #134. should be asking now before asking to save. (please also try to update your branch to latest master)

**Comment by ThomasSmith3** [comment]
Updated and it is working fine.
Not sure if able to combine the two pop windows for exiting if you haven't saved your annotations.
So you would have a single window with 3 options
- Save and exit
- Don't and exit
- cancel
and keep the question the same.

**Comment by tobiasbaur** [comment]
Added in #136
