### ISSUE TITLE
Redundant post-build event declared at the "nova" project

### ISSUE THREAD

**Issue by RC90** [hcmlab/nova#145]
The following post-build event is found declared in the sources of the latest stable release of NOVA (0.9.9.4.6) :

`xcopy /Y ..\bin\nova.exe ..\..\..\bin\x64\vc140`

This command seems redundant to me. It also contains relative path to what seems to be a VS installation, which can vary from one computer to another. This is not critical, however should be addressed, or alternatively added to the documentation / readme.

**Comment by tobiasbaur** [comment]
also fixed in the latest master version.
