### ISSUE TITLE
The latest stable release of NOVA (0.9.9.4.6) crashes when attempting to create a new label for a discrete tier

### ISSUE THREAD

**Issue by RC90** [hcmlab/nova#146]
The latest stable release of NOVA (0.9.9.4.6) crashes when attempting to create a new label for a discrete tier. The crash occurs when loading a video file from local drive, then clicking on the "New Tier" button, selecting "New Discrete Tier" and clicking on the "+" button at the bottom of the window. Debugger points to line 119 in "nova-0.9.9.4.6\dll\LabelInputBox.xaml.cs":

`SolidColorBrush b = AnnoTrack.GetSelectedTrack().BackgroundColor as SolidColorBrush;`

The exception is NullReferenceException and it is described as follows:

> An exception of type 'System.NullReferenceException' occurred in ssiview.dll but was not handled in user code. Additional information: Object reference not set to an instance of an object.

**Comment by tobiasbaur** [comment]
Should be fixed in the latest master build (we are currently still refactoring the code, so as soon as this is finished we will create a new release).
