### ISSUE TITLE
UriFormatException when attempting to save a project created using the latest commit of the master branch

### ISSUE THREAD

**Issue by RC90** [hcmlab/nova#148]
UriFormatException when attempting to save a project created using the latest commit of the master branch in 

`nova-master\Tools\FileTools.cs`

line 66:

`Uri pathUri = new Uri(filespec);`

> An unhandled exception of type 'System.UriFormatException' occurred in System.dll. Additional information: Invalid URI: The format of the URI could not be determined.

**Comment by tobiasbaur** [comment]
should be fixed (was due to refactoring)
