### ISSUE TITLE
Make order of loading and showing tiers consistent

### ISSUE THREAD

**Issue by mvalstar** [hcmlab/nova#179]
I noticed that the order in which annotation tiers are displayed is (semi) random. We played with a number of videos that all had the six basic emotions predicted, but each time I loaded a different video by selecting all annotation files and the source video, the emotion prediction tiers were shown in a different order.

I did not experiment with loading the same video + annotations multiple times, to see if it was truly random.

It would be great if the order was consistent.

**Comment by frankenjoe** [comment]
done
