### ISSUE TITLE
Deleting data should be centralized

### ISSUE THREAD

**Issue by shelm** [hcmlab/nova#290]
Since the database only provides links to files on the local filesystem I need to delete data in two different places if I want to get rid of it - db and fs. Otherwise the data still persists as either the entry in the database (if it has just been deleted from the fs) or on the filesystem without any according entry in the db. (if deleted in the db).
It would be nice to be able to delete data directly from the NOVA-gui in both places.

**Comment by tobiasbaur** [comment]
Done!
