### ISSUE TITLE
Feature extraction loops when it cant find a file

### ISSUE THREAD

**Issue by shelm** [hcmlab/nova#305]
When the feature extraction can't find a file it will retry a few seconds later. This is problematic when calculating computational expensive features (e.g. openface) since Nova will be stuck in that loop till the problem has been resolved manually. This can result in an large loss of effectively used computation time unless the user is willing to check regularly if the pipeline is still running.
Any soft error like this should be nonblocking with enough information in the error log afterwards to see what happend.

**Comment by frankenjoe** [comment]
if a file is not found feature extraction should be skipped. somehow this must be related to openface.

**Comment by frankenjoe** [comment]
solved
