### ISSUE TITLE
Creating custom subsets of sessions

### ISSUE THREAD

**Issue by shelm** [hcmlab/nova#316]
At the moment the training and evaluation process is inconvenient if you want to use different subsets of a corpus for each of the steps since the respective sessions need to be selected manually every time. 
It would be really nice to be able to create custom sets for training, evaluation, development, etc....

**Comment by tobiasbaur** [comment]
Done with .set files. In each line, add a session name of the subset. Place the .set files in the corpus directory (above the sessions)
