### ISSUE TITLE
Possibility to display multiple data streams (time series)

### ISSUE THREAD

**Issue by jardinetsouffleton** [hcmlab/nova#445]
Hi, 
I am using NOVA to annotate time series and was wondering if there was a way multiple time series at the same time. based on what I have seen, it is not possible to display more than one channels at the same time.

Thanks!

![multiple_time_series](https://user-images.githubusercontent.com/30133110/92513409-402dd280-f1de-11ea-9ed2-09279c64568e.gif)

**Comment by tobiasbaur** [comment]
Nova's default behviour is to display one dimension of a stream at a time. In order to achieve what you want (from how I understand), you could open the same stream file twice and select a different dimension for one of these files.

**Comment by jardinetsouffleton** [comment]
Oh right... That works great! Thanks
