### ISSUE TITLE
Wave signal window can not be displayed on windows 7

### ISSUE THREAD

**Issue by bpotard** [hcmlab/nova#79]
On windows 7, when loading a wav file, the application crashes. Video appears to run fine, and I have not tested the other data types.

The relevant part of the actual exception which happens is the following:
{"Could not load file or assembly 'PresentationFramework.Aero2, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.":"PresentationFramework.Aero2, PublicKeyToken=31bf3856ad364e35"}

It appears you explicitly reference the Aero2 framework, which according to Microsoft (cf. https://connect.microsoft.com/VisualStudio/feedback/details/2634836/presentationframework-aero2-not-on-any-win-7) you should never do. You should reference the Aero framework, which will use whatever implementation is available on the guest OS (Aero on Windows 7, Aero2 on Windows 8+). Referencing explicitly forces the application to look like a windows 8 application, which looks ugly on windows 10 and crashes on windows 7.

It would be great to correct that so that Nova can run on windows 7!

**Comment by tobiasbaur** [comment]
Fixed in Commit #80
